/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package blackcode.ui;

import blackcode.uiclass.TableActionEvent;
import blackcode.uiclass.VerticalLabelUI;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author madfox99
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
        cmdLabel.setUI(new VerticalLabelUI(true));
        cmdLabel.setText(new SimpleDateFormat("MMM dd", Locale.ENGLISH).format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdEdit = new blackcode.uiclass.ActionButton();
        cmdDelete = new blackcode.uiclass.ActionButton();
        cmdLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 51, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        cmdEdit.setBackground(new java.awt.Color(51, 51, 51));
        cmdEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackcode/img/Edit_15px.png"))); // NOI18N
        cmdEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdEditMouseEntered(evt);
            }
        });

        cmdDelete.setBackground(new java.awt.Color(51, 51, 51));
        cmdDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blackcode/img/Delete_15px.png"))); // NOI18N
        cmdDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdDeleteMouseEntered(evt);
            }
        });

        cmdLabel.setForeground(new java.awt.Color(255, 204, 0));
        cmdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cmdLabel.setText("Sep 20");
        cmdLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
            .addComponent(cmdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(cmdDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cmdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdEditMouseEntered
        cmdEdit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cmdEditMouseEntered

    private void cmdDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdDeleteMouseEntered
        cmdDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cmdDeleteMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private blackcode.uiclass.ActionButton cmdDelete;
    private blackcode.uiclass.ActionButton cmdEdit;
    private javax.swing.JLabel cmdLabel;
    // End of variables declaration//GEN-END:variables

    public void initEvent(TableActionEvent event, int row) {
        cmdEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        cmdDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    }
}
